version: "3.8"

services:
  test:
    build:
      context: ../..
      dockerfile: infra/etl/Dockerfile.test
    volumes:
      - ../../:/app
    environment:
      - PYTHONPATH=/app
    command: python -m pytest etl/tests/ -m "unit" --maxfail=1 -v
